export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
/* export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const SELECT_EMPLOYEE = 'SELECT_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE'; */